copyright: Copyright &copy; 2016

site_name: Boost.MSM-lite
site_url: http://www.mkdocs.org
site_author: Krzysztof Jusiak
repo_url: https://github.com/boost-experimental/msm-lite
repo_name: msm-lite
docs_dir: .
use_directory_urls: false
theme_dir: boost
google_analytics: ['UA-73083568-1', 'boost-experimental.github.io/msm-lite']
extra_javascript: []
extra_css: []

pages:
- Introduction: index.md
- Overview: overview.md
- Tutorial: tutorial.md
- User Guide: user_guide.md
- Examples: examples.md
- CHANGELOG: CHANGELOG.md
- TODO: TODO.md
