copyright: Copyright &copy; 2016

site_name: Boost.SML
site_url: http://boost-experimental.github.io/msm-lite
site_author: Kris Jusiak
repo_url: https://github.com/boost-experimental/msm-lite
repo_name: msm-lite
docs_dir: .
use_directory_urls: false
theme_dir: themes/boost
google_analytics: ['UA-73083568-1', 'auto']
extra_javascript: []
extra_css: []

pages:
- Introduction: index.md
- Overview: overview.md
- Features/Benchmarks: benchmarks.md
- Tutorial: tutorial.md
- User Guide: user_guide.md
- Examples: examples.md
- CHANGELOG: CHANGELOG.md
- TODO: TODO.md
